version: '3.8'

services:
  rest-api:
    build: ./
    command: ./rest-api
    ports:
      - 8000:8000
    depends_on:
      - mongo
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - SIGNING_KEY=${SIGNING_KEY}

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
